Update system.sh
  File "tools/editconf.py", line 71, in <module>
    input_lines = list(open(filename))
FileNotFoundError: [Errno 2] No such file or directory: '/etc/default/bind9'

--> change to '/etc/default/named'